# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
